FROM golang:1.23 AS builder

WORKDIR /usr/src/app

COPY go.mod main.go ./
RUN go mod download && go mod verify

RUN CGO_ENABLED=0 GOOS=linux go build -a -ldflags="-s -w" -o app .

FROM scratch
COPY --from=builder /usr/src/app/app .

CMD ["./app"]